# sample-workflow-ubuntu-latest
# docs are in the repo

name: .NET Code Analysis ubuntu-latest
on:
  push:
    branches:
      - sonarcloud-pr1-test

jobs:
  sample:
    name: .NET Code Analysis runner

    # .NET Code Analysis runs on windows-latest.
    # ubuntu-latest and macos-latest supporting coming soon
    runs-on: ubuntu-latest

    steps:

      # Checkout your code repository to scan
    - uses: actions/checkout@v4

    # Ensure compatible versions of dotnet are installed.
    # The [Microsoft Code Analysis CLI](https://aka.ms/mscadocs) is built with dotnet v3.1.201.
    # A version greater than or equal to v3.1.201 of dotnet must be installed on the agent in order to run this action.
    # Remote agents already have a compatible version of dotnet installed and this step may be skipped.
    # For local agents, ensure dotnet version 3.1.201 or later is installed by including this action:
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          3.1.x

    # Run NuGet restore for the solution at repo root
    - name: Run NuGet restore
      run: dotnet restore

    # Install guardian
    - name: Install guardian
      run: |
        dotnet add package Microsoft.Security.CodeAnalysis.Cli 
        dotnet tool install -g Guardian

    # Initialize guardian
    - name: Initialize guardian
      run: |
        guardian init

    # Configure guardian for Roslyn Analyzers
    - name: Configure guardian for Roslyn Analyzers
      run: |
        guardian configure -t roslynanalyzers      

    # Run code analysis for the solution at repo root
    - name: Run .NET Code Analysis
      uses: dotnet/code-analysis@main
      id: code-analysis
      with:
        build-breaking: false

    # Upload the analysis results file
    - name: Upload analysis results
      uses: actions/upload-artifact@v2
      with:
        name: analysis_results.sarif
        path: ${{ steps.code-analysis.outputs.sarifFile }}